# Generated by Django 2.2.9 on 2020-02-11 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('mon_id', models.AutoField(primary_key=True, serialize=False)),
                ('plantname', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('humidity', models.CharField(max_length=255)),
                ('water_temp', models.CharField(max_length=255)),
                ('ph', models.CharField(max_length=255)),
                ('motor_status', models.BooleanField(default='Not Found')),
                ('light_status', models.BooleanField(default='Not Found')),
            ],
        ),
        migrations.CreateModel(
            name='usr_profile',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('mobile_number', models.IntegerField()),
                ('designation', models.CharField(max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='audit_log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usr_profile')),
            ],
        ),
    ]
